# Generated by Django 5.1.2 on 2025-02-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_alter_post_time_stamp_follow"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("follower", "following")},
        ),
    ]
