# Generated by Django 5.1.6 on 2025-02-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_alter_follow_follower"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_pics/user.png",
                null=True,
                upload_to="profile_pics",
            ),
        ),
    ]
