# Generated by Django 5.1.6 on 2025-02-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0006_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="default.jpg", null=True, upload_to="profile_pics"
            ),
        ),
    ]
