# Generated by Django 5.1.6 on 2025-02-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0007_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images"),
        ),
    ]
