# Generated by Django 5.1.6 on 2025-03-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0010_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="default_profile.png",
                null=True,
                upload_to="profile_pics",
            ),
        ),
    ]
